### PR TITLE
Creation of mock

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
Out of need.

### CODE REVIEW

**Comment by pzavolinsky** [comment]
Great, @robertleeplummerjr, thanks!

Merged and published as `1.3.1`.

I also did some minor refactor to ease creating add-ons (like `except` and `mock`) in the future. Make sure you sync your fork with my last commit for future contribs.

Cheers!

**Comment by pzavolinsky** [comment]
Hey @robertleeplummerjr your comment in my [commit](https://github.com/pzavolinsky/react-unit/commit/5399494f335e094f1122c223afb655119e8e79e3#commitcomment-16778206) about composing add-ons is absolutely right.

I refactored the code a little and now composition is working (e.g. `.exclude(A).mock(B, C)`)!

That being said, I see some more refactor on the way because the height of the high-order functions is starting to give me vertigo.

Could you test `1.3.2` with your code and see if it works as expected (and I didn't break anything)?

Please let me know if you find anything strange.

Cheers!

**Comment by robertleeplummerjr** [comment]
I'll test it tomorrow morning, thank you for your insight.  This project has been the talk of my team for the past two weeks.  The only way I can think of to simplify this is by going oo, but that is simply because I'm very new to the functional paradigm.

**Comment by robertleeplummerjr** [comment]
Nothing strange, works 100% on our code base.  Nice job and thank you for
your hard work!

On Mon, Mar 21, 2016 at 6:48 PM, Patricio Zavolinsky <
notifications@github.com> wrote:

> Hey @robertleeplummerjr <https://github.com/robertleeplummerjr> your
> comment in my commit
> <https://github.com/pzavolinsky/react-unit/commit/5399494f335e094f1122c223afb655119e8e79e3#commitcomment-16778206>
> about composing add-ons is absolutely right.
>
> I refactored the code a little and now composition is working (e.g. .exclude(A).mock(B,
> C))!
>
> That being said, I see some more refactor on the way because the height of
> the high-order functions is starting to give me vertigo.
>
> Could you test 1.3.2 with your code and see if it works as expected (and
> I didn't break anything)?
>
> Please let me know if you find anything strange.
>
> Cheers!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pzavolinsky/react-unit/pull/17#issuecomment-199522530>
>



-- 
Robert Plummer

**Comment by pzavolinsky** [comment]
That's great!

> This project has been the talk of my team for the past two weeks.

I'm really happy that you find this library as useful as I do!

Thank you @robertleeplummerjr !

**Pull request merged**
