### PR TITLE
provide means of textContent lookup and test

### PR DESCRIPTION
**Pull request by robertleeplummerjr**

### CODE REVIEW

**Comment by pzavolinsky** [comment]
Hehe, thanks @robertleeplummerjr !

Currently `.text` already behaves like `.textContent` so we could replace:
```js
get textContent() {
  let text = this.text || '';
  let children = this.children;

  if (children === null || children.length === 0) return text;

  if (typeof children === 'string') {
    return children + text;
  } else if (children.hasOwnProperty('map')) {
    return children.map((child) => {
      return child.textContent;
    }).join('') + text;
  }
  return text;
}
```

with this:
```js
get textContent() {
  return this.text;
}
```

Am I missing something? Do you see any problems with this simplification? Or, in other words, can you think of a spec that would fail with this second implementation that would pass with first one?

As soon as you get back to me with the good to go (or a counter example) I'll merge the PR and publish a new version.

Cheers!

**Comment by robertleeplummerjr** [comment]
I love the simplification.  Early in my testing I found that text didn't behave as I had thought it would, I was inside the constructor.  But it seems that the magic happens after instantiation (or I clearly didn't understand what was going on, the latter seems more likely), in which case you are totally correct.  Wishes granted.  Thank you for looking into this with haste.

**Comment by pzavolinsky** [comment]
Hey @robertleeplummerjr thanks for the contribution.

Just pushed version `1.1.2` to npm including this change.

Cheers!

**Comment by robertleeplummerjr** [comment]
Thanks again!

**Pull request merged**
