### PR TITLE
Fix texts concatenation (remove extra spaces) - fixes #10

### LINKED ISSUE #10: extra spaces contained in element.text as returned by queries
When components are created, the property `text` is set to the concatenation of its texts.
It works in most cases. However it adds some extra spaces as the code joins texts together by adding spaces.

It makes tests difficult to write.

For instance, consider this simple react component that displays a time period:

```
const DateRange = ({from, to}) => {
  return <div>{from} - {to}</div>
}
```

When testing with the following code:
```
var component = createComponent(<DateRange from="Mon" to="Tue"/>);
expect(component.findByQuery('div')[0].text).to.equal('Mon - Tue');
```

The code fails with the following:
```
AssertionError: expected 'Mon  -  Tue' to equal 'Mon - Tue'
      + expected - actual

      -Mon  -  Tue
      +Mon - Tue
```

### PR DESCRIPTION
**Pull request by bdo**

### CODE REVIEW

**Comment by pzavolinsky** [comment]
Hi @bdo you are absolutely right about this one. 

The normal behavior of .textContent (or $('..').text() for that matter) concats with the empty string.

Your PR is sound and I'm inclined to merge it as-is.

The only thing I'm still trying to figure out is how to do this in an non-disruptive way (i.e. changing the behavior of .text will break existing tests, even if the new behavior is the correct one).

Worst case, I'll have to bump the `minor` version.

Any ideas?

**Comment by bdo** [comment]
Hi Patricio,

I was thinking about it as well. It's not breaking any of your tests, but it could mean some clients will see their tests breaking. So yeah `minor` version seems the right way. Do you want me to bump the minor version number in my pull request or is this something you can do?

**Comment by pzavolinsky** [comment]
Hi @bdo , I'll bump the version after merging your PR.

This change is breaking 0.5% of my tests, but still is somewhat annoying.

I'll probably merge the PR and bump the version tomorrow. And afterwards I'll add the workaround for backwards compat in #10 (namely replace `c.text` with `c.texts.join(' ')`).

I think we should add a scenario to `text.jsx` for something like:

```html
<ul><li>First</li><li>Second</li><li>Third</li></ul>
```

so that we can explicitly assert for:

```js
c.text == "FirstSecondThird"
```

and

```js
c.texts.join(' ') == "First Second Third"
```
Are you up for it? Otherwise, I'll add it tomorrow after merging your PR.

Cheers!

**Comment by bdo** [comment]
I added the following unit test:

```
var TextsAccrossSeveralElements = React.createClass({
  render: function() {
    return <ul><li>1</li><li>2</li><li>3</li></ul>
  }
});

describe('text should be aggregated with no extra spaces added', () => {

  ...

  it('across several elements', () => {
    var component = createComponent(<TextsAccrossSeveralElements/>);
    var texts = component.findByQuery('ul')[0];
    expect(texts.text).toEqual('123');
  });

});
```

**Comment by pzavolinsky** [comment]
Great, thanks!

**Comment by bdo** [comment]
Also bumped the minor version :)

**Comment by pzavolinsky** [comment]
Published version `1.1.0`.

Thanks @bdo !

**Pull request merged**
