### PR TITLE
Add findByComponent which can find children of certain React Class

### PR DESCRIPTION
**Pull request by kamilio**
which is particularly useful when asserting for number of sub-components rendered.

Any feedback is appreciated and also let me know if it is aligned with the vision of the project.

I also added a method `componentProp` to access to original props of the component.

### CODE REVIEW

**Comment by pzavolinsky** [comment]
Hi @kamilio, I'm a bit swamped right now, I'll review the code for this PR next week and let you know. The other PR (reduction of the global scope) is pretty straightforward so I'll check the tests, merge it and publish a new version come Monday.

Cheers!

**Comment by kamilio** [comment]
Hi @pzavolinsky thanks a lot and no worries, take your time. I am using my fork for our project, so it is fine.

I will rebase it meanwhile.

**Comment by kamilio** [comment]
Btw, I would be happy to setup also some Continuous Integration etc.

**Comment by pzavolinsky** [comment]
Hey @kamilio this code is sound and I'm tempted to merge it as-is. The only thing that is making some noise is the duality of `.props` vs. `.componentProps`.

By this I mean that calling `.props` and `.componentProps` on the same object will return different values and this might be a bit confusing.

In my mind it would be ideal if we could avoid adding `.componentProps` and just use `.props`. 

One way I believe we can achieve this is by explicitly using shallow render when creating components. That is (using your example of [Master and friends](https://github.com/pzavolinsky/react-unit/pull/2/files#diff-c0f32db873bdc6a63a7422ea4ea47c53))....

Deep rendering `<SuperMaster/>` (current implementation) yields:

```html
<div><h1>First Child</h1></div>
```

Shallow rendering `<SuperMaster/>` (future implementation, optional behavior) could yield:
```html
<Master/>
```
In this (shallow) mode, we would see React components as regular HTML elements (albeit with weird names) and we could manipulate them the usual way (find them with Sizzle expressions, call `.props`, etc.).

I'm inclined to try this in a separate branch and see what happens. Maybe you can try this branch in your project and let me know if it fits your needs

What do you think?

BTW: I already foresee issues with namespaced components. E.g. `Parent.Child = React.createComponent(...)`) because their name would conflict with dot class selectors in Sizzle (e.g. `<Parent.Child />` selected as `findByQuery('Parent.Child')` would have a different meaning altogether: `<Parent className='Child' />`.

**Comment by pzavolinsky** [comment]
@kamilio I pushed an initial version of alternative rendering modes into the [alt-rendering](https://github.com/pzavolinsky/react-unit/tree/alt-rendering) branch.

It still a little green in the tests and documentation department.

Basically, now we can fine-tune the the rendering process to control the component erasure. 

Given:

```jsx
var Child = React.createClass({
  render: function() { return <h1>{this.props.title}</h1> }
});

var Master = React.createClass({
  render: function() { return <div><Child title="First Child"/></div> }
});
```

By default, `createComponent(<Master/>)` will render all components (current behavior):

```html
<div><h1>First Child</h1></div>
```

And `createComponent.shallow(<Master/>)` will render only a single level of components (similar to the traditional shallowRender from React's TestUtils:

```html
<div><Child title="First Child"/></div>
```

Now things get interesting with `createComponent.interleaved(<Master/>)` that will interleave react components and generated HTML:
```html
<div>
  <Child title="First Child">
    <h1>First Child</h1>
  </Child>
</div>
```

The cool thing about all of these is that you can mix and match components and HTML even in Sizzle selectors! 

For example:

```jsx
    var component = createComponent.shallow(<Master />);
    var child = component.findByQuery('Child[title="First Child"]')[0];
```
or

```jsx
    var component = createComponent.shallow(<Master />);
    var child = component.findByQuery('div > Child > h1')[0];
```

Also we should be able to use `.props` seamlessly in both rendered HTML and react components.

It would be awesome if you could take this for a spin and see if it fit your project's needs.

Any feedback on this would be awesome!

Cheers.

**Comment by kamilio** [comment]
Hi @pzavolinsky I gave it a lot of thoughts last days and came up with very similar idea. To have two types of `createComponent` React shallow and the full default. Interleaved render is very interesting idea, not really my use case. But it certainly opens up the library to many more usages. (if you don't know what to use, just use interleaved) Pretty cool feature.

I think, `findByComponent` could still be a good addition as you can leave out the `Sizzle` and theoretically make it faster, possibly less error because you are using the imported variable rather than string.

I would also consider using shallow render as default, because that is the most suitable option for writing unit tests, at least in my case. 

I will take it for a spin later on today and let you know. But I think it should be all good!

**Comment by pzavolinsky** [comment]
Hi @kamilio, 

> I think, findByComponent could still be a good addition as you can leave out the Sizzle and theoretically make it faster, possibly less error because you are using the imported variable rather than string.

Agreed. I merged your PR into [alt-rendering](https://github.com/pzavolinsky/react-unit/tree/alt-rendering) and updated the README. I enabled `findByComponent` for both shallow and interleaved modes. Is not enabled in default because the components themselves were erased.

Just in case you really **must** use `findByComponent` in default mode I included an `.originalComponentInstance` prop that you can use to implement `findByComponent` and `componentProp` in your tests.

> I would also consider using shallow render as default, because that is the most suitable option for writing unit tests, at least in my case. 

Agreed, this makes a lot of sense. I'm not rushing into this change only because it would break existing tests.

I'm quite confident this branch is ready to merge with master but I'll wait for your feedback.

Cheers.

**Comment by kamilio** [comment]
Hi,

great to hear from you. 

> Just in case you really must use findByComponent in default mode.

I don't have to, you can remove it.

> Agreed, this makes a lot of sense. I'm not rushing into this change only because it would break existing tests.

Sure thing,  if you agree 100% I can issue PR later on, otherwise it's all good. 

> I'm quite confident this branch is ready to merge with master but I'll wait for your feedback.

It's really great, merge it! :+1: Beautiful

**Comment by pzavolinsky** [comment]
Merged into 1.0.7.

Thanks!

**Comment by kamilio** [comment]
Cheers!

**Pull request merged**
