### PR TITLE
added exclude method

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
For more exact unit tests when needed.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Created for when in a situation where a component needs store but you are simply trying to test rendering of a component.  In my situation we had:
```html
<Header>
  <Menu>
    <SpecialMenuItemThatNeedsTested />
    <Notifications />
  </Menu>
</Header
```

`Notifications` is a complex component that needed to be tested, but because it required a store it was next to impossible to test the `SpecialMenuItemThatNeedsTested` without stubbing out/hacking a ton of script.  This allows us to gracefully test our component now by using:

```js
createComponent.exclude(Notifications)(Header);
```

**Comment by pzavolinsky** [comment]
Hi @robertleeplummerjr this looks cool. I'll review the PR today or tomorrow.

Just as a side comment, you can probably achieve similar effects with the following:

```js
describe('SpecialMenuItemThatNeedsTested', () => {
  it('works properly', () => {
    var component = createComponent(<SpecialMenuItemThatNeedsTested />);

    // Act (interact with component)

    // Assert (check the results of the interactions)
  });
});

// This integration test might be overkill if Menu is simple enough to be visually inspected,
// but is included here for completeness sake.
describe('Menu', () => {
  it('renders SpecialMenuItemThatNeedsTested and Notifications with the expected props', () => {
    var menu = createComponent.shallow(<Menu />);

    var specialMenu = menu.findByQuery('SpecialMenuItemThatNeedsTested')[0];
    var notifications = menu.findByQuery('Notifications')[0];

    // Assert specialMenu's props and notifications' props.
    expect(specialMenu.props.items).toEqual([1,2,3]);
  });
});
```

Cheers!

**Comment by robertleeplummerjr** [comment]
I did try using shallow, but because the logic that we were testing against was specific to the `Header` and not to `Menu` I couldn't achieve the depth that I needed.  Too, the depth of the `Notifications` and of `Menu` are equal, so in the end I caved and ended up creating the `exclude` method in this PR, figuring that someone somewhere would need this.
Also, we plan on using the `exclude` method in many other locations within our project.  Thanks for the acknowledgement.

**Comment by robertleeplummerjr** [comment]
No rush, but if this were to make it into the lib me along with several coworkers would be motivated to do several backflip cartwheel highfive cheers.  Also, we would be very greatful.

**Comment by pzavolinsky** [comment]
Hi @robertleeplummerjr ,

>  if this were to make it into the lib me along with several coworkers would be motivated to do several backflip cartwheel highfive cheers

looking forward to it!

Could you make the following changes to your PR?

Housekeeping stuff:

1. rebase against my master (your PR is 4 commits behind)
2. (ideal) squash

Actual changes: it would be great not to rely on the global `exclude` array. We can achieve this by:

1. Extracting `createComponent` as the first arg of `createComponentDeep`, `createComponentShallow` and `createComponentInterleaved`
2. Then:
  ```js
  const createComponentWithExclusion = R.curry(
    (exclude, compCtor, parent, ctor) => {
      return R.contains(ctor.type, exclude)
        ? null
        : createComponent(compCtor, parent, ctor);
    }
  );

  var exportedFn = createComponentDeep(createComponent, null);
  exportedFn.shallow = createComponentShallow(createComponent, null);
  exportedFn.interleaved = createComponentInterleaved(createComponent, null);

  exportedFn.exclude = (_exclude) => {
    const exclude = _exclude.constructor === Array ? _exclude : [_exclude];
    const ccWithExclusion = createComponentWithExclusion(exclude);
    var fn = createComponentDeep(ccWithExclusion, null);
    fn.shallow = createComponentShallow(ccWithExclusion, null);
    fn.interleaved = createComponentInterleaved(ccWithExclusion, null);
    return fn;
  };
  ```

If you do the housekeeping stuff, I'll do the rest, unless you want to give it a try.

Let me know what you think.

Cheers!

**Comment by robertleeplummerjr** [comment]
Housekeeping done.

**Comment by robertleeplummerjr** [comment]
I did try your example, but couldn't seem to get it right.  Does the usage remain the same?

**Comment by pzavolinsky** [comment]
Hi @robertleeplummerjr , it's merged and pushed as `1.2.0`. 

[Here](https://github.com/pzavolinsky/react-unit/commit/5d5bd83dfc63b8e170d98169c703296090ffd441) is the change I mentioned in my previous comment (scroll down to `react-unit.jsx`).

You can post the backflip cartwheel highfive video link below.

Cheers!

**Comment by robertleeplummerjr** [comment]
I just figured it out in my branch and saw this.

**Comment by robertleeplummerjr** [comment]
I'll open a curry-fying pr.

**Comment by robertleeplummerjr** [comment]
nm, I saw your approach, and it is cleaner.

**Comment by robertleeplummerjr** [comment]
^ as promised.

**Pull request merged**
