### PR TITLE
Add findByRef method.

### PR DESCRIPTION
**Pull request by ghengeveld**
Of course this is easy to achieve using findBy(), but since refs are the recommended way to target components in React, it makes sense to have a shortcut for it.

### CODE REVIEW

**Comment by pzavolinsky** [comment]
Cool @ghengeveld , could you add some tests to your PR? 

You can take a look at [these](https://github.com/pzavolinsky/react-unit/blob/master/test/find-by.jsx) for inspiration.

Cheers!

**Comment by ghengeveld** [comment]
Done. I didn't think you'd care much, since findByTag and findByClassName aren't under test either.

**Comment by ghengeveld** [comment]
Perhaps it should be noted that this will only work for string refs, not callback refs. I'm not yet sure how callback refs should be tested.

**Comment by pzavolinsky** [comment]
Great, merged and published as `1.0.12`. Also note that since `1.0.11` you can: 

```js
component.findByQuery('[ref=myRef]')
```

and the same goes for `key` in keyed collections:

```js
component.findByQuery('[key=myKey]')
```

Thank you, @ghengeveld !

**Pull request merged**
